name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Deploy only when pushing to main branch

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  docker-deploy:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/job-autoapply:latest

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/job-autoapply:latest
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'  # Fail the job if high/critical issues found

      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/job-autoapply:latest
